pose0: /create1/scan_match_pose
pose0_config: [
              true, true, false,
              false, false, true,
              false, false, false,
              false, false, false,
              false,  false, false
             ]
# pose0_queue_size: 10
# pose0_nodelay: false
# pose0_differential: false
# pose0_relative: true
