imu0_config: [
              false, false, false,
              false, false, false,
              false, false, false,
              false, false, true,
              false, false, false
             ]
# imu0_queue_size: 10
# imu0_nodelay: false
# imu0_differential: false
imu0_relative: true
imu0_remove_gravitational_acceleration: true
